name: Gradle Hero
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-api
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-manager
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-manager-refactored
    - name: Build with Gradle
      run: ./gradlew gD
      working-directory: theme-park-rides
    - name: Build with Gradle
      run: ./gradlew gD
      working-directory: theme-park-rides-kotlin
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: theme-park-rides-status
    - name: Build with Gradle
      run: ./gradlew gD zD
      working-directory: theme-park-rides-with-zip
    - name: Build with Gradle
      run: ./gradlew gD zD
      working-directory: theme-park-rides-with-zip-fixed
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: file-diff-plugin
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: gradle-in-the-real-world/code-coverage
    - name: Build with Gradle
      run: ./gradlew assemble # deliberately not running check
      working-directory: gradle-in-the-real-world/code-style
    - name: Build with Gradle
      run: ./gradlew assemble # deliberately not running check
      working-directory: gradle-in-the-real-world/code-quality
    - name: Build with Gradle
      run: ./gradlew bootBuildImage
      working-directory: gradle-in-the-real-world/docker-image
    - name: Archive UI
      uses: actions/upload-artifact@v2
      with:
        name: ui
        path: theme-park-manager/ui/build/course-downloadable
        retention-days: 180
    - name: Configure Gradle Build Bible AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::299404798587:role/gradle-build-bible-Role-FATI9KHI61JP
        aws-region: eu-west-1
    - name: Copy downloadable to Gradle Build Bible S3 Bucket
      run: aws s3 cp theme-park-manager/ui/build/ui.zip s3://gradle-build-bible
    - name: Configure Gradle Hero AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::299404798587:role/gradle-hero-Role-KS41B43T74UG
        aws-region: eu-west-1
    - name: Copy downloadable to Gradle Hero S3 Bucket
      run: aws s3 cp theme-park-manager/ui/build/ui.zip s3://gradle-hero